name: Deploy API

# Author: @minff
# Issue : n/a
# Desc  : This workflow deploy API to gh-pages

# run this on push to main
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-mobidatalab:
    uses: mobidatalab/mdl-catalog-deployment/.github/workflows/base_deploy.yaml@main
    with:
      api-repo: mobidatalab/mdl-catalog-api
      cache-repo: APIs-guru/openapi-directory
